const actionTypes = {
  CREATE_MINION: "CREATE_MINION",
  DESTROY_MINION: "DESTROY_MINION",

  CREATE_TEAM: "CREATE_TEAM",
  DESTROY_TEAM: "DESTROY_TEAM",

  SAVE: "SAVE",
  AUTO_ENROLL: "AUTO_ENROLL",
};

export default actionTypes;
